# Generated by Django 3.2 on 2024-10-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Слаг'),
        ),
    ]
