# Generated by Django 3.2 on 2024-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_genre_title_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='titles', to='api.Genre', verbose_name='Жанр'),
        ),
    ]
