# Generated by Django 3.2 on 2024-10-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241022_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title_id',
            new_name='title',
        ),
    ]
